/* 
=================================================================================
DDL Script : Create Bronze Tables
=================================================================================
Script Purpose
  This script creates tables in the 'bronze' schema, dropping existing tables if they already exists
  Run this script to re-define the DDL structure of 'bronze' Tables
=================================================================================
*/

-- Drop and recreate the 'DataWarehouse' database
IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'DataWarehouse')
Begin
	ALTER DATABASE DataWarehouse SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE DataWarehouse;
END;



--Create the 'DataWarehouse' database

CREATE Database Datawarehouse;
USE Datawarehouse;

CREATE SCHEMA bronze;
CREATE SCHEMA silver;
CREATE SCHEMA gold;


IF OBJECT_ID ('bronze.crm_cust_info','U') IS NOT NULL
	DROP TABLE bronze.crm_cust_info;
CREATE TABLE bronze.crm_cust_info(
		cst_id INT,
		cst_key NVARCHAR(50),
		cst_firstname NVARCHAR(50),
		cst_lastname NVARCHAR(50),
		cst_marritial_status NVARCHAR(50),
		cst_gndr NVARCHAR(50),
		cst_create_date DATE);

IF OBJECT_ID ('bronze.crm_prd_info','U') IS NOT NULL
	DROP TABLE bronze.crm_prd_info;
CREATE TABLE bronze.crm_prd_info(
		prd_id        INT,
		prd_key       NVARCHAR(50),
		prd_nm        NVARCHAR(50),
		prd_cost      INT,
		prd_line      NVARCHAR(50),
		prd_start_dt  DATETIME,
		prd_end_dt    DATETIME);

IF OBJECT_ID ('bronze.crm_sales_details','U') IS NOT NULL
	DROP TABLE bronze.crm_sales_details;
CREATE TABLE bronze.crm_sales_details (
		sls_ord_num   NVARCHAR(50),
		sls_prd_key   NVARCHAR(50),
		sls_cust_id   INT,
		sls_order_dt  INT,
		sls_ship_dt   INT,
		sls_due_dt    INT,
		sls_sales     INT,
		sls_quantity  INT,
		sls_price     INT);

IF OBJECT_ID ('bronze.erp_loc_a101','U') IS NOT NULL
	DROP TABLE bronze.erp_loc_a101;
CREATE TABLE bronze.erp_loc_a101(
		cid   NVARCHAR(50),
		cntry NVARCHAR(50));


IF OBJECT_ID ('bronze.erp_cust_az12','U') IS NOT NULL
	DROP TABLE bronze.erp_cust_az12;
CREATE TABLE bronze.erp_cust_az12(
		cid   NVARCHAR(50),
		bdate DATE,
		gen NVARCHAR(50));


IF OBJECT_ID ('bronze.erp_px_cat_g1v2','U') IS NOT NULL
	DROP TABLE bronze.erp_px_cat_g1v2;
CREATE TABLE bronze.erp_px_cat_g1v2(
		id           NVARCHAR(50),
		cat          NVARCHAR(50),
		subcat       NVARCHAR(50),
		maintenance  NVARCHAR(50)
		);

CREATE OR ALTER PROCEDURE bronze.load_bronze AS
BEGIN
	DECLARE @batch_start_time DATETIME, @batch_end_time DATETIME;
	BEGIN TRY
		SET @batch_start_time = GETDATE();
		PRINT '====================================================';
		PRINT 'Loading Bronze Layer';
		print '====================================================';

		PRINT '----------------------------------------------------';
		PRINT 'Loading CRM Tables'
		PRINT '----------------------------------------------------';
	
		declare @start_time DATETIME, @end_time DATETIME;
		--bronze.crm_cust_info
		SET @start_time = GETDATE();
		PRINT '>> Truncating Table: bronze.crm_cust_info';
		TRUNCATE TABLE bronze.crm_cust_info;

		PRINT '>> Inserting Data into : bronze.crm_cust_info';
		BULK INSERT bronze.crm_cust_info
		FROM 'C:\Users\hanif\Desktop\Business Analysis\Data warehousing project\source_crm\cust_info.csv'
		WITH ( 
				FIRSTROW = 2,
				FIELDTERMINATOR = ',',
				TABLOCK 
				);
		SET @end_time = GETDATE();
		PRINT '>> Load Duration: '+ CAST(DATEDIFF(second, @start_time, @end_time) as NVARCHAR) + 'seconds';
		PRINT '>> ----------------------------------------------';

		--SELECT * FROM bronze.crm_cust_info;
		--SELECT COUNT (*) FROM bronze.crm_cust_info;


		--bronze.crm_prd_info
		SET @start_time = GETDATE();
		PRINT '>> Truncating Table: bronze.crm_prd_info';
		TRUNCATE TABLE bronze.crm_prd_info;

		PRINT '>> Inserting Data into : bronze.crm_prd_info';
		BULK INSERT bronze.crm_prd_info
		FROM 'C:\Users\hanif\Desktop\Business Analysis\Data warehousing project\source_crm\prd_info.csv'
		WITH ( 
				FIRSTROW = 2,
				FIELDTERMINATOR = ',',
				TABLOCK 
				);
		SET @end_time = GETDATE();
		PRINT '>> Load Duration: '+ CAST(DATEDIFF(second, @start_time, @end_time) as NVARCHAR) + 'seconds';
		PRINT '>> ----------------------------------------------';

		--SELECT * FROM bronze.crm_prd_info;
		--SELECT COUNT (*) FROM bronze.crm_prd_info;


		--bronze.crm_sales_details
		SET @start_time = GETDATE();
		PRINT '>> Truncating Table: bronze.crm_sales_details';
		TRUNCATE TABLE bronze.crm_sales_details;

		PRINT '>> Inserting Data into : bronze.crm_sales_details';
		BULK INSERT bronze.crm_sales_details
		FROM 'C:\Users\hanif\Desktop\Business Analysis\Data warehousing project\source_crm\sales_details.csv'
		WITH ( 
				FIRSTROW = 2,
				FIELDTERMINATOR = ',',
				TABLOCK 
				);
		SET @end_time = GETDATE();
		PRINT '>> Load Duration: '+ CAST(DATEDIFF(second, @start_time, @end_time) as NVARCHAR) + 'seconds';
		PRINT '>> ----------------------------------------------';

		--SELECT * FROM bronze.crm_sales_details
		--SELECT COUNT (*) FROM bronze.crm_sales_details;


		PRINT '----------------------------------------------------';
		PRINT 'Loading ERP Tables'
		PRINT '----------------------------------------------------';
	
		--bronze.erp_loc_a101
		SET @start_time = GETDATE();
		PRINT '>> Truncating Table: bronze.erp_loc_a101';
		TRUNCATE TABLE bronze.erp_loc_a101;
	
		PRINT '>> Inserting Data into : bronze.erp_loc_a101';
		BULK INSERT bronze.erp_loc_a101
		FROM 'C:\Users\hanif\Desktop\Business Analysis\Data warehousing project\source_erp\LOC_A101.csv'
		WITH ( 
				FIRSTROW = 2,
				FIELDTERMINATOR = ',',
				TABLOCK 
				);
		SET @end_time = GETDATE();
		PRINT '>> Load Duration: '+ CAST(DATEDIFF(second, @start_time, @end_time) as NVARCHAR) + 'seconds';
		PRINT '>> ----------------------------------------------';

		--SELECT * FROM bronze.erp_loc_a101
		--SELECT COUNT (*) FROM bronze.erp_loc_a101;


		--bronze.erp_cust_az12
		SET @start_time = GETDATE();
		PRINT '>> Truncating Table: bronze.erp_cust_az12';
		TRUNCATE TABLE bronze.erp_cust_az12;
	
		PRINT '>> Inserting Data into : bronze.erp_cust_az12';
		BULK INSERT bronze.erp_cust_az12
		FROM 'C:\Users\hanif\Desktop\Business Analysis\Data warehousing project\source_erp\CUST_AZ12.csv'
		WITH ( 
				FIRSTROW = 2,
				FIELDTERMINATOR = ',',
				TABLOCK 
				);
		SET @end_time = GETDATE();
		PRINT '>> Load Duration: '+ CAST(DATEDIFF(second, @start_time, @end_time) as NVARCHAR) + 'seconds';
		PRINT '>> ----------------------------------------------';

		--SELECT * FROM bronze.erp_cust_az12
		--SELECT COUNT (*) FROM bronze.erp_cust_az12;

		--bronze.erp_px_cat_g1v2
		SET @start_time = GETDATE();
		PRINT '>> Truncating Table: bronze.erp_px_cat_g1v2';
		TRUNCATE TABLE bronze.erp_px_cat_g1v2;
	
		PRINT '>> Inserting Data into : bronze.erp_px_cat_g1v2';
		BULK INSERT bronze.erp_px_cat_g1v2
		FROM 'C:\Users\hanif\Desktop\Business Analysis\Data warehousing project\source_erp\PX_CAT_G1V2.csv'
		WITH ( 
				FIRSTROW = 2,
				FIELDTERMINATOR = ',',
				TABLOCK 
				);
		SET @end_time = GETDATE();
		PRINT '>> Load Duration: '+ CAST(DATEDIFF(second, @start_time, @end_time) as NVARCHAR) + 'seconds';
		PRINT '>> ----------------------------------------------';

		--SELECT * FROM bronze.erp_px_cat_g1v2
		--SELECT COUNT (*) FROM bronze.erp_px_cat_g1v2;
		SET @batch_end_time = GETDATE();
		PRINT '====================================================';
		PRINT '>> Bronze layer - Total Load Batch processing Duration: '+ CAST(DATEDIFF(second, @batch_start_time, @batch_end_time) as NVARCHAR) + 'seconds';
		print '====================================================';
	END TRY
	BEGIN CATCH
		PRINT '========================================================'
		PRINT 'ERROR OCCURED DURING LOADING BRONZE LAYER'
		PRINT '========================================================'
		PRINT 'ERROR Message' + ERROR_MESSAGE();
		PRINT 'ERROR Message' + CAST(ERROR_NUMBER() AS NVARCHAR);
		PRINT 'ERROR Message' + CAST(ERROR_STATE() AS NVARCHAR);
		PRINT '========================================================'
	END CATCH
END

EXEC bronze.load_bronze
