/* 
============================================================================================
Stored Procedure: Load Bronze Layer (Source -> Bronze)
============================================================================================
Script Purpose:
  This stored procedure loads data into the 'bronze' schema from external CSV files.
  It performs the following actions:
  - Trancates the bronze tables before loading data.
  - Uses the 'BULK INSERT command to load data from csv Files to bronze tables.

Parameters:
  None.
  This stored procedure does not accept any parameters or return any values.

Usage Example:
  EXEC bronze.load_bronze;
  ==========================================================================================
  */

  CREATE OR ALTER PROCEDURE bronze.load_bronze AS
BEGIN
	DECLARE @batch_start_time DATETIME, @batch_end_time DATETIME;
	BEGIN TRY
		SET @batch_start_time = GETDATE();
		PRINT '====================================================';
		PRINT 'Loading Bronze Layer';
		print '====================================================';

		PRINT '----------------------------------------------------';
		PRINT 'Loading CRM Tables'
		PRINT '----------------------------------------------------';
	
		declare @start_time DATETIME, @end_time DATETIME;
		--bronze.crm_cust_info
		SET @start_time = GETDATE();
		PRINT '>> Truncating Table: bronze.crm_cust_info';
		TRUNCATE TABLE bronze.crm_cust_info;

		PRINT '>> Inserting Data into : bronze.crm_cust_info';
		BULK INSERT bronze.crm_cust_info
		FROM 'C:\Users\hanif\Desktop\Business Analysis\Data warehousing project\source_crm\cust_info.csv'
		WITH ( 
				FIRSTROW = 2,
				FIELDTERMINATOR = ',',
				TABLOCK 
				);
		SET @end_time = GETDATE();
		PRINT '>> Load Duration: '+ CAST(DATEDIFF(second, @start_time, @end_time) as NVARCHAR) + 'seconds';
		PRINT '>> ----------------------------------------------';

		--SELECT * FROM bronze.crm_cust_info;
		--SELECT COUNT (*) FROM bronze.crm_cust_info;


		--bronze.crm_prd_info
		SET @start_time = GETDATE();
		PRINT '>> Truncating Table: bronze.crm_prd_info';
		TRUNCATE TABLE bronze.crm_prd_info;

		PRINT '>> Inserting Data into : bronze.crm_prd_info';
		BULK INSERT bronze.crm_prd_info
		FROM 'C:\Users\hanif\Desktop\Business Analysis\Data warehousing project\source_crm\prd_info.csv'
		WITH ( 
				FIRSTROW = 2,
				FIELDTERMINATOR = ',',
				TABLOCK 
				);
		SET @end_time = GETDATE();
		PRINT '>> Load Duration: '+ CAST(DATEDIFF(second, @start_time, @end_time) as NVARCHAR) + 'seconds';
		PRINT '>> ----------------------------------------------';

		--SELECT * FROM bronze.crm_prd_info;
		--SELECT COUNT (*) FROM bronze.crm_prd_info;


		--bronze.crm_sales_details
		SET @start_time = GETDATE();
		PRINT '>> Truncating Table: bronze.crm_sales_details';
		TRUNCATE TABLE bronze.crm_sales_details;

		PRINT '>> Inserting Data into : bronze.crm_sales_details';
		BULK INSERT bronze.crm_sales_details
		FROM 'C:\Users\hanif\Desktop\Business Analysis\Data warehousing project\source_crm\sales_details.csv'
		WITH ( 
				FIRSTROW = 2,
				FIELDTERMINATOR = ',',
				TABLOCK 
				);
		SET @end_time = GETDATE();
		PRINT '>> Load Duration: '+ CAST(DATEDIFF(second, @start_time, @end_time) as NVARCHAR) + 'seconds';
		PRINT '>> ----------------------------------------------';

		--SELECT * FROM bronze.crm_sales_details
		--SELECT COUNT (*) FROM bronze.crm_sales_details;


		PRINT '----------------------------------------------------';
		PRINT 'Loading ERP Tables'
		PRINT '----------------------------------------------------';
	
		--bronze.erp_loc_a101
		SET @start_time = GETDATE();
		PRINT '>> Truncating Table: bronze.erp_loc_a101';
		TRUNCATE TABLE bronze.erp_loc_a101;
	
		PRINT '>> Inserting Data into : bronze.erp_loc_a101';
		BULK INSERT bronze.erp_loc_a101
		FROM 'C:\Users\hanif\Desktop\Business Analysis\Data warehousing project\source_erp\LOC_A101.csv'
		WITH ( 
				FIRSTROW = 2,
				FIELDTERMINATOR = ',',
				TABLOCK 
				);
		SET @end_time = GETDATE();
		PRINT '>> Load Duration: '+ CAST(DATEDIFF(second, @start_time, @end_time) as NVARCHAR) + 'seconds';
		PRINT '>> ----------------------------------------------';

		--SELECT * FROM bronze.erp_loc_a101
		--SELECT COUNT (*) FROM bronze.erp_loc_a101;


		--bronze.erp_cust_az12
		SET @start_time = GETDATE();
		PRINT '>> Truncating Table: bronze.erp_cust_az12';
		TRUNCATE TABLE bronze.erp_cust_az12;
	
		PRINT '>> Inserting Data into : bronze.erp_cust_az12';
		BULK INSERT bronze.erp_cust_az12
		FROM 'C:\Users\hanif\Desktop\Business Analysis\Data warehousing project\source_erp\CUST_AZ12.csv'
		WITH ( 
				FIRSTROW = 2,
				FIELDTERMINATOR = ',',
				TABLOCK 
				);
		SET @end_time = GETDATE();
		PRINT '>> Load Duration: '+ CAST(DATEDIFF(second, @start_time, @end_time) as NVARCHAR) + 'seconds';
		PRINT '>> ----------------------------------------------';

		--SELECT * FROM bronze.erp_cust_az12
		--SELECT COUNT (*) FROM bronze.erp_cust_az12;

		--bronze.erp_px_cat_g1v2
		SET @start_time = GETDATE();
		PRINT '>> Truncating Table: bronze.erp_px_cat_g1v2';
		TRUNCATE TABLE bronze.erp_px_cat_g1v2;
	
		PRINT '>> Inserting Data into : bronze.erp_px_cat_g1v2';
		BULK INSERT bronze.erp_px_cat_g1v2
		FROM 'C:\Users\hanif\Desktop\Business Analysis\Data warehousing project\source_erp\PX_CAT_G1V2.csv'
		WITH ( 
				FIRSTROW = 2,
				FIELDTERMINATOR = ',',
				TABLOCK 
				);
		SET @end_time = GETDATE();
		PRINT '>> Load Duration: '+ CAST(DATEDIFF(second, @start_time, @end_time) as NVARCHAR) + 'seconds';
		PRINT '>> ----------------------------------------------';

		--SELECT * FROM bronze.erp_px_cat_g1v2
		--SELECT COUNT (*) FROM bronze.erp_px_cat_g1v2;
		SET @batch_end_time = GETDATE();
		PRINT '====================================================';
		PRINT '>> Bronze layer - Total Load Batch processing Duration: '+ CAST(DATEDIFF(second, @batch_start_time, @batch_end_time) as NVARCHAR) + 'seconds';
		print '====================================================';
	END TRY
	BEGIN CATCH
		PRINT '========================================================'
		PRINT 'ERROR OCCURED DURING LOADING BRONZE LAYER'
		PRINT '========================================================'
		PRINT 'ERROR Message' + ERROR_MESSAGE();
		PRINT 'ERROR Message' + CAST(ERROR_NUMBER() AS NVARCHAR);
		PRINT 'ERROR Message' + CAST(ERROR_STATE() AS NVARCHAR);
		PRINT '========================================================'
	END CATCH
END

EXEC bronze.load_bronze
